version: '3'

services:
  app:
    build:
      context: ./experise
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8081:8081"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

