# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  security:
      runs-on: ubuntu-latest
      steps:
        - name: Set up JDK 11
        - uses: actions/setup-java@v1
          with:
            java-version: 11
          
        - uses: actions/checkout@main
        - name: Change wrapper permissions
          run: chmod +x ./mvnw
          
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/node@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            command: monitor
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: ssh-pipeline
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          # ssh remote host
          host: ${{ secrets.HOST }} 
          # ssh remote port
          port: ${{ secrets.PORT }} 
          # ssh remote user
          user: ${{ secrets.USERNAME }} 
          # content of ssh private key. ex raw content of ~/.ssh/id_rsa
          key: ${{ secrets.KEY }} 
          # ssh remote password
          pass: ${{ secrets.PASS }} 
          # connection timeout to remote host
          connect_timeout: 30s
          # execute commands on ssh
          script: |
            cd 
